#!/bin/bash
echo "TYPE random parameters"
echo "LIST random parameters"
echo "CDIR random parameters"
echo "KILL random parameters"
echo "NAME random parameters"
echo "DONE random parameters"
echo "RETR random parameters"
echo "STOR random parameters"
echo "user 1"
echo "done"